[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = [
    "cd backend && npm install && npx prisma generate && npm run build",
    "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd frontend && npm start"
