[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x"]

[phases.build]
cmds = ["npm install", "cd backend && npx prisma generate", "cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"
